---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    platform: linux/amd64
    image: ubuntu:24.04
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: rocky
    platform: linux/amd64
    image: rockylinux:8
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
