---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    platform: linux/amd64
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: rockylinux
    platform: linux/amd64
    image: rockylinux:9
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
